### ISSUE TITLE
Crash after turning on BT

### ISSUE THREAD

**Issue by kjkrum** [ligi/BLExplorer#4]
If BT is off when the app is started, it asks for permission to turn it on.  If you say yes, it immediately crashes:

```
E/AndroidRuntime(28510): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2300, result=-1, data=null} to activity {org.ligi.blexplorer/org.ligi.blexplorer.scan.DeviceListActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(28510):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3659)
E/AndroidRuntime(28510):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3702)
E/AndroidRuntime(28510):        at android.app.ActivityThread.access$1300(ActivityThread.java:155)
E/AndroidRuntime(28510):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
E/AndroidRuntime(28510):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(28510):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(28510):        at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(28510):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28510):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28510):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(28510):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(28510): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(28510):        at org.ligi.blexplorer.scan.DeviceListActivity.onActivityResult(DeviceListActivity.kt)
E/AndroidRuntime(28510):        at android.app.Activity.dispatchActivityResult(Activity.java:6218)
E/AndroidRuntime(28510):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3655)
E/AndroidRuntime(28510):        ... 10 more
```
This does not occur if BT is already on when the app is started.

Motorola XT1032, Android 5.1

**Comment by cweiske** [comment]
Happens here with android 6.0.1

**Comment by leopornorecio** [comment]
****
